# fly.toml app configuration file generated for ccap-dir on 2024-01-26T17:45:37+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ccap-dir'
primary_region = 'hkg'
console_command = 'deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts'

[build]

[env]
  PORT = '8080'

[processes]
  app = 'run -A ./index.tsx'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  processes = ['app']
