export type Locality = {
    key: string
    displayName: string
}

export const LOCALITY: Locality[] = [
  { "key": "ADELAIDE", "displayName": "Adelaide" },
  { "key": "ALBANY", "displayName": "Albany" },
  { "key": "ALBURY-WODONGA", "displayName": "Albury-Wodonga" },
  { "key": "ALICE SPRINGS", "displayName": "Alice Springs" },
  { "key": "ALPHA", "displayName": "Alpha" },
  { "key": "AMATA", "displayName": "Amata" },
  { "key": "ANDAMOOKA", "displayName": "Andamooka" },
  { "key": "ANGURUGU", "displayName": "Angurugu" },
  { "key": "ARARAT", "displayName": "Ararat" },
  { "key": "ARMIDALE", "displayName": "Armidale" },
  { "key": "ATHERTON", "displayName": "Atherton" },
  { "key": "AUGATHELLA", "displayName": "Augathella" },
  { "key": "AUGUSTA", "displayName": "Augusta" },
  { "key": "AURUKUN", "displayName": "Aurukun" },
  { "key": "AYR", "displayName": "Ayr" },
  { "key": "BAIRNSDALE", "displayName": "Bairnsdale" },
  { "key": "BALLADONIA HOTEL-MOTEL", "displayName": "Balladonia Hotel-Motel" },
  { "key": "BALLARAT", "displayName": "Ballarat" },
  { "key": "BALLINA", "displayName": "Ballina" },
  { "key": "BALRANALD", "displayName": "Balranald" },
  { "key": "BAMAGA", "displayName": "Bamaga" },
  { "key": "BAMYILI", "displayName": "Bamyili" },
  { "key": "BARCALDINE", "displayName": "Barcaldine" },
  {
    "key": "BARKLY HOMESTEAD ROADHOUSE",
    "displayName": "Barkly Homestead Roadhouse",
  },
  { "key": "BATCHELOR", "displayName": "Batchelor" },
  { "key": "BATEMANS BAY", "displayName": "Batemans Bay" },
  { "key": "BATHURST", "displayName": "Bathurst" },
  { "key": "BEAUDESERT", "displayName": "Beaudesert" },
  { "key": "BEGA", "displayName": "Bega" },
  { "key": "BENALLA", "displayName": "Benalla" },
  { "key": "BENDIGO", "displayName": "Bendigo" },
  { "key": "BERRI", "displayName": "Berri" },
  { "key": "BEVERLEY", "displayName": "Beverley" },
  { "key": "BILOELA", "displayName": "Biloela" },
  { "key": "BIRDSVILLE", "displayName": "Birdsville" },
  { "key": "BLACKALL", "displayName": "Blackall" },
  { "key": "BLACKWATER", "displayName": "Blackwater" },
  { "key": "BORDERTOWN", "displayName": "Bordertown" },
  { "key": "BORROLOOLA", "displayName": "Borroloola" },
  { "key": "BOULIA", "displayName": "Boulia" },
  { "key": "BOURKE", "displayName": "Bourke" },
  { "key": "BOWEN", "displayName": "Bowen" },
  { "key": "BOWRAL", "displayName": "Bowral" },
  { "key": "BREWARRINA", "displayName": "Brewarrina" },
  { "key": "BRIDGEWATER", "displayName": "Bridgewater" },
  { "key": "BRISBANE", "displayName": "Brisbane" },
  { "key": "BROKEN HILL", "displayName": "Broken Hill" },
  { "key": "BROOME", "displayName": "Broome" },
  { "key": "BUNBURY", "displayName": "Bunbury" },
  { "key": "BUNDABERG", "displayName": "Bundaberg" },
  { "key": "BURKETOWN", "displayName": "Burketown" },
  { "key": "BURNIE", "displayName": "Burnie" },
  { "key": "BURRA", "displayName": "Burra" },
  { "key": "BUSSELTON", "displayName": "Busselton" },
  { "key": "CABOOLTURE", "displayName": "Caboolture" },
  { "key": "CAIRNS", "displayName": "Cairns" },
  { "key": "CALOUNDRA", "displayName": "Caloundra" },
  { "key": "CAMDEN", "displayName": "Camden" },
  { "key": "CAMOOWEAL", "displayName": "Camooweal" },
  { "key": "CAMPBELL TOWN", "displayName": "Campbell Town" },
  { "key": "CANBERRA", "displayName": "Canberra" },
  { "key": "CARNARVON", "displayName": "Carnarvon" },
  { "key": "CASINO", "displayName": "Casino" },
  { "key": "CEDUNA", "displayName": "Ceduna" },
  { "key": "CENTRAL COAST", "displayName": "Central Coast" },
  { "key": "CESSNOCK", "displayName": "Cessnock" },
  { "key": "CHARLEVILLE", "displayName": "Charleville" },
  { "key": "CHARTERS TOWERS", "displayName": "Charters Towers" },
  { "key": "CHINCHILLA", "displayName": "Chinchilla" },
  { "key": "CLARE", "displayName": "Clare" },
  { "key": "CLERMONT", "displayName": "Clermont" },
  { "key": "CLEVE", "displayName": "Cleve" },
  { "key": "CLONCURRY", "displayName": "Cloncurry" },
  { "key": "COBAR", "displayName": "Cobar" },
  { "key": "COFFS HARBOUR", "displayName": "Coffs Harbour" },
  { "key": "COLAC", "displayName": "Colac" },
  { "key": "COLLARENEBRI", "displayName": "Collarenebri" },
  { "key": "COLLIE", "displayName": "Collie" },
  { "key": "COLLINSVILLE", "displayName": "Collinsville" },
  { "key": "CONDOBOLIN", "displayName": "Condobolin" },
  { "key": "COOBER PEDY", "displayName": "Coober Pedy" },
  { "key": "COOK", "displayName": "Cook" },
  { "key": "COOLGARDIE", "displayName": "Coolgardie" },
  { "key": "COOMA", "displayName": "Cooma" },
  { "key": "COONABARABRAN", "displayName": "Coonabarabran" },
  { "key": "COONAMBLE", "displayName": "Coonamble" },
  { "key": "COOTAMUNDRA", "displayName": "Cootamundra" },
  { "key": "COROWA", "displayName": "Corowa" },
  { "key": "CORRIGIN", "displayName": "Corrigin" },
  { "key": "COWRA", "displayName": "Cowra" },
  { "key": "CRANBOURNE", "displayName": "Cranbourne" },
  { "key": "CUNNAMULLA", "displayName": "Cunnamulla" },
  { "key": "CYGNET", "displayName": "Cygnet" },
  { "key": "DALBY", "displayName": "Dalby" },
  { "key": "DALWALLINU", "displayName": "Dalwallinu" },
  { "key": "DALY RIVER", "displayName": "Daly River" },
  { "key": "DAMPIER", "displayName": "Dampier" },
  { "key": "DARWIN", "displayName": "Darwin" },
  { "key": "DEAKIN", "displayName": "Deakin" },
  { "key": "DENHAM", "displayName": "Denham" },
  { "key": "DENILIQUIN", "displayName": "Deniliquin" },
  { "key": "DENMARK", "displayName": "Denmark" },
  { "key": "DERBY", "displayName": "Derby" },
  { "key": "DEVONPORT", "displayName": "Devonport" },
  { "key": "DIRRANBANDI", "displayName": "Dirranbandi" },
  {
    "key": "DOCKER RIVER (KALTUKATJARA)",
    "displayName": "Docker River (kaltukatjara)",
  },
  { "key": "DONGARA", "displayName": "Dongara" },
  { "key": "DOOMADGEE", "displayName": "Doomadgee" },
  { "key": "DUBBO", "displayName": "Dubbo" },
  { "key": "DUNMARRA", "displayName": "Dunmarra" },
  { "key": "DYSART", "displayName": "Dysart" },
  { "key": "ECHUCA", "displayName": "Echuca" },
  { "key": "EDEN", "displayName": "Eden" },
  { "key": "ELLIOTT", "displayName": "Elliott" },
  { "key": "EMERALD", "displayName": "Emerald" },
  { "key": "ENEABBA", "displayName": "Eneabba" },
  { "key": "ERLDUNDA", "displayName": "Erldunda" },
  { "key": "ESPERANCE", "displayName": "Esperance" },
  { "key": "EUCLA", "displayName": "Eucla" },
  { "key": "FITZROY CROSSING", "displayName": "Fitzroy Crossing" },
  { "key": "FORBES", "displayName": "Forbes" },
  { "key": "FORSTER-TUNCURRY", "displayName": "Forster-Tuncurry" },
  { "key": "GATTON", "displayName": "Gatton" },
  { "key": "GAWLER", "displayName": "Gawler" },
  { "key": "GAYNDAH", "displayName": "Gayndah" },
  { "key": "GEELONG", "displayName": "Geelong" },
  { "key": "GEORGETOWN", "displayName": "Georgetown" },
  { "key": "GILGANDRA", "displayName": "Gilgandra" },
  { "key": "GLADSTONE", "displayName": "Gladstone" },
  { "key": "GLEN INNES", "displayName": "Glen Innes" },
  { "key": "GNOWANGERUP", "displayName": "Gnowangerup" },
  { "key": "GOLD COAST", "displayName": "Gold Coast" },
  { "key": "GOOMALLING", "displayName": "Goomalling" },
  { "key": "GOONDIWINDI", "displayName": "Goondiwindi" },
  { "key": "GOULBURN", "displayName": "Goulburn" },
  { "key": "GRAFTON", "displayName": "Grafton" },
  { "key": "GREENVALE", "displayName": "Greenvale" },
  { "key": "GRIFFITH", "displayName": "Griffith" },
  { "key": "GUNNEDAH", "displayName": "Gunnedah" },
  { "key": "GYMPIE", "displayName": "Gympie" },
  { "key": "HALLS CREEK", "displayName": "Halls Creek" },
  { "key": "HAMILTON", "displayName": "Hamilton" },
  { "key": "HARVEY", "displayName": "Harvey" },
  { "key": "HAWKER", "displayName": "Hawker" },
  { "key": "HAY", "displayName": "Hay" },
  { "key": "HELENVALE", "displayName": "Helenvale" },
  { "key": "HERMANNSBURG", "displayName": "Hermannsburg" },
  { "key": "HERVEY BAY", "displayName": "Hervey Bay" },
  { "key": "HOBART", "displayName": "Hobart" },
  { "key": "HOME HILL", "displayName": "Home Hill" },
  { "key": "HORSHAM", "displayName": "Horsham" },
  { "key": "HUGHENDEN", "displayName": "Hughenden" },
  { "key": "INGHAM", "displayName": "Ingham" },
  { "key": "INNAMINCKA", "displayName": "Innamincka" },
  { "key": "INNISFAIL", "displayName": "Innisfail" },
  { "key": "INVERELL", "displayName": "Inverell" },
  { "key": "IVANHOE", "displayName": "Ivanhoe" },
  { "key": "JABIRU", "displayName": "Jabiru" },
  { "key": "JERRAMUNGUP", "displayName": "Jerramungup" },
  { "key": "JULIA CREEK", "displayName": "Julia Creek" },
  { "key": "JURIEN", "displayName": "Jurien" },
  { "key": "KADINA", "displayName": "Kadina" },
  { "key": "KALGOORLIE-BOULDER", "displayName": "Kalgoorlie-Boulder" },
  { "key": "KALKARINDJI", "displayName": "Kalkarindji" },
  { "key": "KAMBALDA", "displayName": "Kambalda" },
  { "key": "KARRATHA", "displayName": "Karratha" },
  { "key": "KARUMBA", "displayName": "Karumba" },
  { "key": "KATANNING", "displayName": "Katanning" },
  { "key": "KATHERINE", "displayName": "Katherine" },
  { "key": "KATOOMBA", "displayName": "Katoomba" },
  { "key": "KEITH", "displayName": "Keith" },
  { "key": "KELLERBERRIN", "displayName": "Kellerberrin" },
  { "key": "KEMPSEY", "displayName": "Kempsey" },
  { "key": "KIAMA", "displayName": "Kiama" },
  { "key": "KIMBA", "displayName": "Kimba" },
  { "key": "KINGAROY", "displayName": "Kingaroy" },
  { "key": "KINGSTON", "displayName": "Kingston" },
  { "key": "KINGSTON S.E.", "displayName": "Kingston S.e." },
  { "key": "KOJONUP", "displayName": "Kojonup" },
  { "key": "KOWANYAMA", "displayName": "Kowanyama" },
  { "key": "KUNUNURRA", "displayName": "Kununurra" },
  { "key": "KURRI KURRI", "displayName": "Kurri Kurri" },
  { "key": "KWINANA", "displayName": "Kwinana" },
  { "key": "KYABRAM", "displayName": "Kyabram" },
  { "key": "LAGRANGE", "displayName": "Lagrange" },
  { "key": "LAJAMANU", "displayName": "Lajamanu" },
  { "key": "LAKE GRACE", "displayName": "Lake Grace" },
  { "key": "LAUNCESTON", "displayName": "Launceston" },
  { "key": "LAVERTON", "displayName": "Laverton" },
  { "key": "LEETON", "displayName": "Leeton" },
  { "key": "LEIGH CREEK", "displayName": "Leigh Creek" },
  { "key": "LEINSTER", "displayName": "Leinster" },
  { "key": "LEONORA", "displayName": "Leonora" },
  { "key": "LIGHTNING RIDGE", "displayName": "Lightning Ridge" },
  { "key": "LISMORE", "displayName": "Lismore" },
  { "key": "LITHGOW", "displayName": "Lithgow" },
  { "key": "LOCKHART RIVER", "displayName": "Lockhart River" },
  { "key": "LONGREACH", "displayName": "Longreach" },
  { "key": "LOOMA", "displayName": "Looma" },
  { "key": "MACKAY", "displayName": "Mackay" },
  { "key": "MADURA", "displayName": "Madura" },
  { "key": "MAITLAND", "displayName": "Maitland" },
  { "key": "MANDURAH", "displayName": "Mandurah" },
  { "key": "MANJIMUP", "displayName": "Manjimup" },
  { "key": "MARBLE BAR", "displayName": "Marble Bar" },
  { "key": "MAREEBA", "displayName": "Mareeba" },
  { "key": "MARGARET RIVER", "displayName": "Margaret River" },
  { "key": "MARREE", "displayName": "Marree" },
  { "key": "MEEKATHARRA", "displayName": "Meekatharra" },
  { "key": "MELBOURNE", "displayName": "Melbourne" },
  { "key": "MELTON", "displayName": "Melton" },
  { "key": "MENINDEE", "displayName": "Menindee" },
  { "key": "MERIMBULA", "displayName": "Merimbula" },
  { "key": "MERREDIN", "displayName": "Merredin" },
  { "key": "MIDDLEMOUNT", "displayName": "Middlemount" },
  { "key": "MILDURA", "displayName": "Mildura" },
  { "key": "MILES", "displayName": "Miles" },
  { "key": "MILIKAPITI", "displayName": "Milikapiti" },
  { "key": "MILLICENT", "displayName": "Millicent" },
  { "key": "MITCHELL", "displayName": "Mitchell" },
  { "key": "MOE", "displayName": "Moe" },
  { "key": "MONTO", "displayName": "Monto" },
  { "key": "MOORA", "displayName": "Moora" },
  { "key": "MORANBAH", "displayName": "Moranbah" },
  { "key": "MORAWA", "displayName": "Morawa" },
  { "key": "MOREE", "displayName": "Moree" },
  { "key": "MOSSMAN", "displayName": "Mossman" },
  { "key": "MOUNT BARKER", "displayName": "Mount Barker" },
  { "key": "MOUNT GAMBIER", "displayName": "Mount Gambier" },
  { "key": "MOUNT MAGNET", "displayName": "Mount Magnet" },
  { "key": "MOUNT MORGAN", "displayName": "Mount Morgan" },
  { "key": "MOURA", "displayName": "Moura" },
  { "key": "MUDGEE", "displayName": "Mudgee" },
  { "key": "MULLEWA", "displayName": "Mullewa" },
  { "key": "MURGON", "displayName": "Murgon" },
  { "key": "MURRAY BRIDGE", "displayName": "Murray Bridge" },
  { "key": "MURWILLUMBAH", "displayName": "Murwillumbah" },
  { "key": "MUSWELLBROOK", "displayName": "Muswellbrook" },
  { "key": "NAMBOUR", "displayName": "Nambour" },
  { "key": "NAMBUCCA HEADS", "displayName": "Nambucca Heads" },
  { "key": "NANANGO", "displayName": "Nanango" },
  { "key": "NARACOORTE", "displayName": "Naracoorte" },
  { "key": "NARRABRI", "displayName": "Narrabri" },
  { "key": "NARRANDERA", "displayName": "Narrandera" },
  { "key": "NEW NORFOLK", "displayName": "New Norfolk" },
  { "key": "NEWCASTLE", "displayName": "Newcastle" },
  { "key": "NEWDEGATE", "displayName": "Newdegate" },
  { "key": "NEWMAN", "displayName": "Newman" },
  { "key": "NGUIU", "displayName": "Nguiu" },
  { "key": "NGUKURR", "displayName": "Ngukurr" },
  { "key": "NHILL", "displayName": "Nhill" },
  { "key": "NHULUNBUY", "displayName": "Nhulunbuy" },
  { "key": "NORMANTON", "displayName": "Normanton" },
  { "key": "NORSEMAN", "displayName": "Norseman" },
  { "key": "NORTHAM", "displayName": "Northam" },
  { "key": "NORTHAMPTON", "displayName": "Northampton" },
  { "key": "NOWRA-BOMADERRY", "displayName": "Nowra-Bomaderry" },
  { "key": "NULLARBOR MOTEL", "displayName": "Nullarbor Motel" },
  { "key": "NURIOOTPA", "displayName": "Nuriootpa" },
  { "key": "NYNGAN", "displayName": "Nyngan" },
  { "key": "OAKEY", "displayName": "Oakey" },
  { "key": "OENPELLI", "displayName": "Oenpelli" },
  { "key": "ONSLOW", "displayName": "Onslow" },
  { "key": "OODNADATTA", "displayName": "Oodnadatta" },
  { "key": "ORANGE", "displayName": "Orange" },
  { "key": "ORROROO", "displayName": "Orroroo" },
  { "key": "OUYEN", "displayName": "Ouyen" },
  { "key": "PANNAWONICA", "displayName": "Pannawonica" },
  { "key": "PAPUNYA", "displayName": "Papunya" },
  { "key": "PARABURDOO", "displayName": "Paraburdoo" },
  { "key": "PARINGA", "displayName": "Paringa" },
  { "key": "PARKES", "displayName": "Parkes" },
  { "key": "PENOLA", "displayName": "Penola" },
  { "key": "PENONG", "displayName": "Penong" },
  { "key": "PERTH", "displayName": "Perth" },
  { "key": "PETERBOROUGH", "displayName": "Peterborough" },
  { "key": "PINE CREEK", "displayName": "Pine Creek" },
  { "key": "PINGELLY", "displayName": "Pingelly" },
  { "key": "PINJARRA", "displayName": "Pinjarra" },
  { "key": "PINNAROO", "displayName": "Pinnaroo" },
  { "key": "PORT AUGUSTA", "displayName": "Port Augusta" },
  { "key": "PORT LINCOLN", "displayName": "Port Lincoln" },
  { "key": "PORT MACQUARIE", "displayName": "Port Macquarie" },
  { "key": "PORT PIRIE", "displayName": "Port Pirie" },
  { "key": "PORTLAND", "displayName": "Portland" },
  { "key": "PROSERPINE", "displayName": "Proserpine" },
  { "key": "QUAIRADING", "displayName": "Quairading" },
  { "key": "QUEANBEYAN", "displayName": "Queanbeyan" },
  { "key": "QUEENSTOWN", "displayName": "Queenstown" },
  { "key": "QUILPIE", "displayName": "Quilpie" },
  { "key": "QUIRINDI", "displayName": "Quirindi" },
  { "key": "QUORN", "displayName": "Quorn" },
  { "key": "RAMINGINING", "displayName": "Ramingining" },
  { "key": "RAVENSTHORPE", "displayName": "Ravensthorpe" },
  { "key": "RAWLINNA", "displayName": "Rawlinna" },
  { "key": "RED CLIFFS", "displayName": "Red Cliffs" },
  { "key": "RENMARK", "displayName": "Renmark" },
  { "key": "RENNER SPRINGS", "displayName": "Renner Springs" },
  { "key": "RICHMOND", "displayName": "Richmond" },
  { "key": "ROCKHAMPTON", "displayName": "Rockhampton" },
  { "key": "ROCKINGHAM", "displayName": "Rockingham" },
  { "key": "ROEBOURNE", "displayName": "Roebourne" },
  { "key": "ROMA", "displayName": "Roma" },
  { "key": "ROSEBERY", "displayName": "Rosebery" },
  { "key": "SALE", "displayName": "Sale" },
  { "key": "SANTA TERESA", "displayName": "Santa Teresa" },
  { "key": "SARINA", "displayName": "Sarina" },
  { "key": "SAWTELL", "displayName": "Sawtell" },
  { "key": "SCONE", "displayName": "Scone" },
  { "key": "SHEPPARTON", "displayName": "Shepparton" },
  { "key": "SINGLETON", "displayName": "Singleton" },
  { "key": "SMITHTON", "displayName": "Smithton" },
  { "key": "SOUTHERN CROSS", "displayName": "Southern Cross" },
  { "key": "SPRINGSURE", "displayName": "Springsure" },
  { "key": "ST GEORGE", "displayName": "St George" },
  { "key": "ST MARYS", "displayName": "St Marys" },
  { "key": "STAMFORD", "displayName": "Stamford" },
  { "key": "STANTHORPE", "displayName": "Stanthorpe" },
  { "key": "STREAKY BAY", "displayName": "Streaky Bay" },
  { "key": "SUNBURY", "displayName": "Sunbury" },
  { "key": "SURAT", "displayName": "Surat" },
  { "key": "SWAN HILL", "displayName": "Swan Hill" },
  { "key": "SYDNEY", "displayName": "Sydney" },
  { "key": "TAMBO", "displayName": "Tambo" },
  { "key": "TAMWORTH", "displayName": "Tamworth" },
  { "key": "TARA", "displayName": "Tara" },
  { "key": "TARCOOLA", "displayName": "Tarcoola" },
  { "key": "TAREE", "displayName": "Taree" },
  { "key": "TAROOM", "displayName": "Taroom" },
  { "key": "TELFER MINING CENTRE", "displayName": "Telfer Mining Centre" },
  { "key": "TENNANT CREEK", "displayName": "Tennant Creek" },
  { "key": "TENTERFIELD", "displayName": "Tenterfield" },
  { "key": "TEWANTIN-NOOSA", "displayName": "Tewantin-Noosa" },
  { "key": "THARGOMINDAH", "displayName": "Thargomindah" },
  { "key": "THREE SPRINGS", "displayName": "Three Springs" },
  { "key": "TOM PRICE", "displayName": "Tom Price" },
  { "key": "TOOWOOMBA", "displayName": "Toowoomba" },
  { "key": "TRARALGON", "displayName": "Traralgon" },
  { "key": "TULLY", "displayName": "Tully" },
  { "key": "TUMBY BAY", "displayName": "Tumby Bay" },
  { "key": "TUMUT", "displayName": "Tumut" },
  { "key": "TURKEY CREEK", "displayName": "Turkey Creek" },
  { "key": "TWEED HEADS", "displayName": "Tweed Heads" },
  { "key": "ULLADULLA", "displayName": "Ulladulla" },
  { "key": "ULVERSTONE", "displayName": "Ulverstone" },
  { "key": "VICTOR HARBOR", "displayName": "Victor Harbor" },
  { "key": "WAGGA WAGGA", "displayName": "Wagga Wagga" },
  { "key": "WAGIN", "displayName": "Wagin" },
  { "key": "WALGETT", "displayName": "Walgett" },
  { "key": "WANGARATTA", "displayName": "Wangaratta" },
  { "key": "WARBURTON", "displayName": "Warburton" },
  { "key": "WARRACKNABEAL", "displayName": "Warracknabeal" },
  { "key": "WARREGO", "displayName": "Warrego" },
  { "key": "WARRNAMBOOL", "displayName": "Warrnambool" },
  { "key": "WARWICK", "displayName": "Warwick" },
  { "key": "WAUCHOPE", "displayName": "Wauchope" },
  { "key": "WELLINGTON", "displayName": "Wellington" },
  { "key": "WENTWORTH", "displayName": "Wentworth" },
  { "key": "WEST WYALONG", "displayName": "West Wyalong" },
  { "key": "WHITE CLIFFS", "displayName": "White Cliffs" },
  { "key": "WHYALLA", "displayName": "Whyalla" },
  { "key": "WILCANNIA", "displayName": "Wilcannia" },
  { "key": "WILUNA", "displayName": "Wiluna" },
  { "key": "WINDORAH", "displayName": "Windorah" },
  { "key": "WINTON", "displayName": "Winton" },
  { "key": "WITTENOOM GORGE", "displayName": "Wittenoom Gorge" },
  { "key": "WOLLONGONG", "displayName": "Wollongong" },
  { "key": "WONGAN HILLS", "displayName": "Wongan Hills" },
  { "key": "WONTHAGGI", "displayName": "Wonthaggi" },
  { "key": "WOOMERA", "displayName": "Woomera" },
  { "key": "WOORABINDA", "displayName": "Woorabinda" },
  { "key": "WUDINNA", "displayName": "Wudinna" },
  { "key": "WYALKATCHEM", "displayName": "Wyalkatchem" },
  { "key": "WYNDHAM", "displayName": "Wyndham" },
  { "key": "WYNYARD", "displayName": "Wynyard" },
  { "key": "YAMBA", "displayName": "Yamba" },
  { "key": "YANCHEP BEACH", "displayName": "Yanchep Beach" },
  { "key": "YEPPOON", "displayName": "Yeppoon" },
  { "key": "YIRRKALA", "displayName": "Yirrkala" },
  { "key": "YORK", "displayName": "York" },
  { "key": "YORKETOWN", "displayName": "Yorketown" },
  { "key": "YOUNG", "displayName": "Young" },
  { "key": "YUENDUMU", "displayName": "Yuendumu" },
  { "key": "YULARA TOURIST VILLAGE", "displayName": "Yulara Tourist Village" },
] as const;

// const text = await Deno.readTextFile("temp.txt");
//
// const rows = text.split("\n");
//
// type locality = {
//   key: string;
//   displayName: string;
// };
//
// const regex = /<option value="(.*)">(.*)<\/option>/;
// const foo: locality[] = [];
//
// rows.map((row) => {
//   const match = row.match(regex);
//   if (match) {
//
//     const displayName = match[2].toLowerCase().replace(
//       /(^|-|\s)(\w)/g,
//       (x) => x.toUpperCase(),
//     );
//     foo.push(
//       {
//         key: match[1],
//         displayName: displayName,
//       },
//     );
//   }
// });
//
// const json = JSON.stringify(foo);
//
// const bytes = new TextEncoder().encode(json);
// const file = await Deno.create("locality.json");
// const written = await file.write(bytes);

